export enum HanoiError {
  BackgroundColorClassesArrayEmpty = "The background color classes array is empty.",
  CannotMoveDiskFromEmptyTower = "A disk cannot be moved from an empty tower.",
  CannotMoveDiskToSameTower = "A disk cannot be moved to the same tower.",
  CannotMoveLargerDiskOntoSmallerDisk = "A larger disk cannot be moved onto a smaller disk.",
  CannotRemoveTopDiskFromEmptyTower = "The top disk cannot be removed from an empty tower.",
  InvalidInitialDiskPosition = "The initial position of a disk cannot be negative.",
  InvalidNotificationType = "The notification type is invalid.",
  InvalidStartRodNumber = "The start rod number must be between 0 and 2.",
  InvalidTotalDisks = "The total number of disks cannot be negative.",
  MinimumNumberOfDisksNotMet = "The number of disks must be at least 3.",
  TowerContentHasNoDisks = "The tower content does not have any disks.",
  TowerContentNotFound = "The tower content could not be found.",
  TowerContentNotFoundForTowerNumber = "The tower content for tower number %s could not be found.",
  TowerContentsArrayEmpty = "The tower contents array is empty.",
}
